### PR TITLE
RCAL-702: Fix memory use issue for Cas22 jump detection

### PR DESCRIPTION
**Pull request by WilliamJamieson**
Resolves [RCAL-702](https://jira.stsci.edu/browse/RCAL-702)

This PR resolves a massive memory spike as part of the solution to RCAL-702

**Checklist**
- [ ] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

### CODE REVIEW

**Review by schlafly — APPROVED** [review]
Looks good to me, thanks!

**Comment by schlafly** [comment]
@stscieisenhamer , mind checking to see if this resolves your issue?  Thanks!

**Review by kmacdonald-stsci — APPROVED** [review]

**Review by stscieisenhamer — APPROVED** [review]
Dramatic change in memory usage: From 150GB to not even breaking 1GB.

And also, there is an actual run-time difference in running with and without `--use_jump_detection`. Without the step runs ~1.5 minutes. With jump detection, the task runs about as long as before this fix, ~6 minutes. As a reminder, before the runtime was no different between the two.

LGTM

**Comment by schlafly** [comment]
I think I see that with include_diagnostic=False we don't get any information back about where the jumps are and we don't end up updating the DQ array.  I think we need that.  Ideally that could happen in place on the DQ array, so no additional memory were needed; I'm not sure how convenient that ends up being here.

**Pull request merged**
