### PR TITLE
JP-3734: Changed Default CI Test Algorithm to OLS_C

### PR DESCRIPTION
**Pull request by kmacdonald-stsci**
Resolves [JP-3734](https://jira.stsci.edu/browse/JP-3734)

Closes #

This PR addresses default algorithm testing for ramp fitting.  The OLS_C algorithm is now the default algorithm for testing.

This PR also addresses a bug that resulted in incorrect attempts to do the CHARGELOSS recalculations when not needed, which would result in a crash when trying to dereference a `NULL` pointer for `rd->orig_gdq`.

The PR revealed another bug in the creation of the optional results product.  The arrays were being created using `PyArray_EMPTY`, which didn't initialize memory, so unused elements in some of the optional results product arrays were junk.  The creation function used now is `PyArray_ZEROS`, which initializes the array to zero.

## Tasks
- [ ] update or add relevant tests
- [ ] update relevant docstrings and / or `docs/` page
- [ ] Does this PR change any API used downstream? (if not, label with `no-changelog-entry-needed`)
  - [ ] write news fragment(s) in `changes/`: `echo "changed something" > changes/<PR#>.<changetype>.rst` (see below for change types)
  - [ ] run regression tests with this branch installed (`"git+https://github.com/<fork>/stcal@<branch>"`)
    - [ ] [`jwst` regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst.yml) 
    - [ ] [`romancal` regression test](https://github.com/spacetelescope/RegressionTests/actions/workflows/romancal.yml)

<details><summary>news fragment change types...</summary>

- ``changes/<PR#>.apichange.rst``: change to public API
- ``changes/<PR#>.bugfix.rst``: fixes an issue
- ``changes/<PR#>.general.rst``: infrastructure or miscellaneous change
</details>

### CODE REVIEW

**Comment by kmacdonald-stsci** [comment]
Regression test:

https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1769/

**Comment by kmacdonald-stsci** [comment]
I recreated the `orig_gdq` error noted in 

https://github.com/spacetelescope/jwst/issues/8842

using the `main` branch using the command 

`strun calwebb_detector1 jw01523003001_03102_00001_mirifulong_uncal.fits --steps.ramp_fit.maximum_cores=half`

I verified this PR fixes this error.

**Review by tapastro — APPROVED** [review]
Looks good to me!

**Comment by tapastro** [comment]
@schlafly I believe this PR touches code that Roman also uses, and it looks like Dave is OoO. Are you willing to review this?

**Comment by schlafly** [comment]
Thanks.  We turned off the "ordinary" ramp fitting unit tests in romancal ~last month, and for our regression tests we use the Casertano+22 stuff, so I doubt this affects Roman.  But I am running some regtests now.

**Comment by schlafly** [comment]
This ran fine on the Roman side, thanks!
https://github.com/spacetelescope/RegressionTests/actions/runs/11238326482/job/31242982194

**Review by schlafly — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
