### PR TITLE
JP-2796: Made style changes due to new flake8 5.0.3

### PR DESCRIPTION
**Pull request by kmacdonald-stsci**
Resolves [JP-2796](https://jira.stsci.edu/browse/JP-2796)

Closes #

This PR addresses style issues related to flake8 error E275, as well as parentheses usage.

**Checklist**
- [x] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [x] added relevant label(s)

### CODE REVIEW

**Comment by hbushouse** [comment]
Please run the jwst regtests against this PR branch to make sure we aren't changing any behaviors. Instructions are at https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches

**Review by hbushouse — COMMENTED** [review]
Code changes look fine, but withholding final approval until we see regtest results.

**Review by dmggh — APPROVED** [review]
Looks good to me.

**Review by cshanahan1 — APPROVED** [review]
looks good

**Pull request merged**
