### PR TITLE
Move common jump code to stcal (RCAL-152).

### PR DESCRIPTION
**Pull request by dmggh**
Modified jump code to be common code within STCAL. Modified DQ flags to be retrieved from either ROMANCAL or JWST. I still need to commit updated CHANGES.rst from a different PR, as it is in a different (ROMANCAL) repo. After this is merged, romancal unit tests will be filed under RCAL-114 .

### CODE REVIEW

**Review by ddavis-stsci — APPROVED** [review]
LGTM now with the fixes.

**Comment by nden** [comment]
Should #23 be closed?

**Comment by dmggh** [comment]
Yes, once this PR (#27) is approved a 2nd time and merged, I was planning to close #23, which this supercedes.

**Review by nden — APPROVED** [review]

**Comment by nden** [comment]
Approved but let's give @cshanahan1 a chance to look at it.

**Comment by cshanahan1** [comment]
My only comments (which I discussed with @dmggh on Slack) are that having a 'constants.py' file for each step individually might not be the best solution to accomplish what it does, but it works for now. 

Otherwise, I think this looks good. Any other comments about the routines I made are in #23, but those were all addressed.

**Review by cshanahan1 — APPROVED** [review]

**Pull request merged**
