### PR TITLE
Remove `dqflags` and related code.

### PR DESCRIPTION
**Pull request by WilliamJamieson**
This PR removes the code moved to `stdatamodels` in spacetelescope/stdatamodels#134. I don't think any of the `dqflags` related code is actually used outside the `jwst` pipeline, so this should not effect any packages.

Note, I replaced the removed code with thin wrapper modules which raise a deprecation warning and then attempt to import from `stdatamodels`, raising a useful error if that import fails.

Closes #145

**Checklist**
- [x] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [x] updated relevant tests
- [ ] updated relevant documentation
- [x] updated relevant milestone(s)
- [x] added relevant label(s)

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Converting to a draft because spacetelescope/stdatamodels#134 needs to be merged and released before these changes will fully work.

**Review by kmacdonald-stsci — APPROVED** [review]

**Review by PaulHuwe — CHANGES_REQUESTED** [review]
Should more dependencies be added to tox.ini? When I run STCAL tests, I get the following errors:

FAILED tests/test_dq.py::test_deprecation[dqflags] - ImportError: dqflags has been moved to stdatamodels.dqflags, please install stdatamodels
FAILED tests/test_dq.py::test_deprecation[dynamicdq] - ImportError: dynamicdq has been moved to stdatamodels.dynamicdq, please install stdatamodels
FAILED tests/test_dq.py::test_deprecation[basic_utils] - ImportError: basic_utils has been moved to stdatamodels.basic_utils, please install stdatamodels

**Comment by WilliamJamieson** [comment]
> Should more dependencies be added to tox.ini? When I run STCAL tests, I get the following errors:
> 
> FAILED tests/test_dq.py::test_deprecation[dqflags] - ImportError: dqflags has been moved to stdatamodels.dqflags, please install stdatamodels FAILED tests/test_dq.py::test_deprecation[dynamicdq] - ImportError: dynamicdq has been moved to stdatamodels.dynamicdq, please install stdatamodels FAILED tests/test_dq.py::test_deprecation[basic_utils] - ImportError: basic_utils has been moved to stdatamodels.basic_utils, please install stdatamodels

I don't think you have the right things installed, you need to try re-installing.

**Comment by PaulHuwe** [comment]
> Details

Turns out that having too old a version of stdatamodels installed caused this.

**Comment by WilliamJamieson** [comment]
> > Details
> 
> Turns out that having too old a version of stdatamodels installed caused this.

If stdatamodels is not installed at all, no error will be raised.

**Comment by PaulHuwe** [comment]
> Details

After some further investigation, I figured it out. With an unsupported version of stdatamodels installed, tox would work, but pytest would fail with what I pasted above. Romancal installs stdatamodels via the stpipe dependency. 

When I installed the development version of stdatamodels, things worked fine.

**Review by PaulHuwe — APPROVED** [review]
With dev stdatamodels, this passes all romancal unit and regression tests.

**Review by hbushouse — APPROVED** [review]
Do we need a new release of stdatamodels before a new release of stcal?

**Comment by WilliamJamieson** [comment]
> Do we need a new release of stdatamodels before a new release of stcal?

Yes

**Review by hbushouse — APPROVED** [review]

**Comment by hbushouse** [comment]
Is there a way to get the 3 queued CI tests to start?

**Comment by WilliamJamieson** [comment]
> Is there a way to get the 3 queued CI tests to start?

Short answer is no, the spacetelescope organization has a very limited number of macos runners, so if lots of PRs in spacetelescope are made, those can get really backed up.

I'm not sure why we have so many macos jobs across all our CI. In general you only really need one to make sure we aren't making assumptions that macos cannot handle, not one on every single version of python.

@zacharyburnett can provide more information.

**Comment by zacharyburnett** [comment]
> > Is there a way to get the 3 queued CI tests to start?
> 
> Short answer is no, the spacetelescope organization has a very limited number of macos runners, so if lots of PRs in spacetelescope are made, those can get really backed up.
> 
> I'm not sure why we have so many macos jobs across all our CI. In general you only really need one to make sure we aren't making assumptions that macos cannot handle, not one on every single version of python.
> 
> @zacharyburnett can provide more information.

That's a fair point; I added macos jobs for thoroughness but you're right, we have limited resources available for free. If you guys are okay with it, I can make some PRs removing macos jobs for Python versions less than latest across the organization.

**Comment by WilliamJamieson** [comment]
> That's a fair point; I added macos jobs for thoroughness but you're right, we have limited resources available for free.

"free" is a strong statement, I don't know exactly how STScI has structured the org, but in general an organization only gets so many minutes of action time per month before they start having to pay for it, see https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions for more details.
Note also that macOS actions have a 10x multiplier on their run time to get how many minutes they cost.

**Comment by WilliamJamieson** [comment]
> Well, at this point I'm satisfied that this works OK and hence am willing to merge without waiting for those remaining CI tests to complete. @WilliamJamieson you're hereby authorized to merge.

I would love to but I don't have the rights in `stcal` to merge things if the branch protections have not passed. So I'll just set the automerge, and it will merge when the protections pass.

@kmacdonald-stsci might be able to override the protections.

**Comment by hbushouse** [comment]
> > Well, at this point I'm satisfied that this works OK and hence am willing to merge without waiting for those remaining CI tests to complete. @WilliamJamieson you're hereby authorized to merge.
> 
> I would love to but I don't have the rights in `stcal` to merge things if the branch protections have not passed. So I'll just set the automerge, and it will merge when the protections pass.
> 
> @kmacdonald-stsci might be able to override the protections.

I have the power. Merging now.

**Pull request merged**
