### PR TITLE
documentation changes + docs for jump detection 

### LINKED ISSUE #17: Add docs
The CI has a doc build, but there's no docs.

### PR DESCRIPTION
**Pull request by cshanahan1**
This PR has a few changes.

1. Changes the directory structure of the docs - no more 'source' dir the conf.py and index.rst files are in the main doc directory, and there is now a '_build' directory. Added a stcal subdirectory and a package_index.rst to eventually hold all the documentation for code. 
2.  Added the first docs for jump detection in docs/stcal/jump
3. Modified the existing default Makefile.

Closes #17

### CODE REVIEW

**Comment by nden** [comment]
Try adding a `readthedocs.yml file` (example in the jwst repo).
Also does `conf.py` need to import `sphinx`?

**Comment by jdavies-st** [comment]
This looks good.  It looks like we need to get rtd to actually build `stcal` for us.  Any idea on how to do this?

**Comment by cshanahan1** [comment]
@jdavies-st i'm trying to figure that out, stay tuned!

**Comment by nden** [comment]
Merging in an attempt to get rtd to build.

**Pull request merged**
