### PR TITLE
Add ramp fit

### PR DESCRIPTION
**Pull request by kmacdonald-stsci**
Copied JWST ramp fitting to STCAL, along with unit tests.

### CODE REVIEW

**Review by dmggh — COMMENTED** [review]
I'm looking at this in conjunction with your related PR#5983. I notice that some files ramp_fit.py, ols_fit.py) to be moved from JWST to STCAL are importing JWST datamodels , including its RampModel -  is this temporary ?

**Comment by kmacdonald-stsci** [comment]
I don’t know why, but I can’t reply to this on github.  There is no reply button, so I’m replying through Outlook.

Yes.  This is just temporary.  I am not done removing all JWST dependencies, yet.  I didn’t want to close the PR while I did this work.  The code will be ready by Monday morning.  I will work this weekend to remove all JWST dependencies in the STCAL rampfit, such as the datamodels and the RampModel dependencies.  In short, the code is not yet done.  I opened this PR to show people the code in order for people to comment on what work needs to be done or should be done.

From: dmggh ***@***.***>
Reply-To: spacetelescope/stcal ***@***.***>
Date: Friday, April 30, 2021 at 8:03 PM
To: spacetelescope/stcal ***@***.***>
Cc: Kenneth MacDonald ***@***.***>, Author ***@***.***>
Subject: Re: [spacetelescope/stcal] Add ramp fit (#4)


@dmggh commented on this pull request.

I'm looking at this in conjunction with your related PR#5983. I notice that some files ramp_fit.py, ols_fit.py) to be moved from JWST to STCAL are importing JWST datamodels , including its RampModel - is this temporary ?

**Comment by dmggh** [comment]
Hi Ken,


OK, great. That's what I thought ; I just wanted to make sure I understood.

By the way, you should be able to 'reply' in GitHub using the 'Leave a comment' field at the bottom of the ticket.


Thanks,

Dave

________________________________

**Review by dmggh — APPROVED** [review]
Looks good to me.

**Review by dmggh — COMMENTED** [review]
I realize this is a work in progress; this looks good so far.

**Comment by kmacdonald-stsci** [comment]
This PR is deprecated.

**Pull request closed without merging**
