### PR TITLE
Install dev wheels properly

### PR DESCRIPTION
**Pull request by pllim**
You can simplify devdeps calls and you can also install astropy dev from wheel.

### CODE REVIEW

**Review by kmacdonald-stsci — APPROVED** [review]

**Review by WilliamJamieson — APPROVED** [review]

**Review by zacharyburnett — COMMENTED** [review]
this looks good to me, for what it's worth

**Comment by pllim** [comment]
I added a commit due to:

* https://github.com/astropy/astropy/issues/15638

**Comment by zacharyburnett** [comment]
> But do you actually use devdeps? I don't see it in the jobs here.

#213 adds devdeps as an optional workflow when adding the `run devdeps tests` label, but it isn't merged yet

**Comment by pllim** [comment]
OK, then maybe you can merge this first and see if this setup really works on your other PR. 🤞 

Or feel free to cherry pick the commits over and close this without merge.

**Pull request merged**
