### PR TITLE
JP-3368: Changing ramp_fit Median Rate and Variance Calculations

### LINKED ISSUE #192: Incorrect Variances for Suppressed Integrations
For this test:
https://github.com/spacetelescope/stcal/blob/7f0a4647fbd7ff4246550d170b2ee6e0c6281ab7/tests/test_ramp_fitting.py#L1253

The computation of the variances are wrong.   A number of the integrations should be suppressed, which should result in the rateints variances being equal to zero for these integrations.  This effects the computation of the image variances as well.

### LINKED ISSUE #203: Median Rate Computation Should Not Include DO_NOT_USE Groups
Currently the computation of the median rates excludes only SATURATED groups, but it should exclude DO_NOT_USE groups as well.

### PR DESCRIPTION
**Pull request by kmacdonald-stsci**
Resolves [JP-3368](https://jira.stsci.edu/browse/JP-3368)

Closes #203 
Closes #192 

This PR corrects the calculations of median rates and variance calculations.  These errors were found during the C implementation for special cases.

Originally, the median rates excluded SATURATED flagged groups, but should exclude DO_NOT_USE flagged groups as well.  This change affects slope and Poisson variance calculations.

Also, for invalid integrations, non-zero variances were computed, but they should be 0.0.  This had already been properly handled for slope calculations in a previous PR addressing JP-3004.  Unfortunately, improper calculation of rateints and rate variances continued. 

**Checklist**
- [x] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [x] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [x] added relevant label(s)

### CODE REVIEW

**Review by hbushouse — COMMENTED** [review]
Looks good. Let's get a full regtest run, which I'm assuming will result in expected differences in at least some tests.

**Comment by nden** [comment]
Roman regression tests pass (except an expected unrelated failure):
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/346/

**Comment by kmacdonald-stsci** [comment]
> https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/916

I expect there to be many failures, especially for MIRI tests.  I ran regression tests showing many failures that looked to be expected failures.  I don't know how to search the Jenkins to figure out which test that was.

**Comment by hbushouse** [comment]
regtest run 916 showed many differences in ERR and variance arrays, especially VAR_POISSON, which appears to be expected.

**Review by hbushouse — APPROVED** [review]

**Pull request merged**
